B445 Fix NoClassDefFoundError for IOUtils
Remove IOUtils usage in OracleClobDataType, preventing no class found
for certain situations due to class residing in transitive dep.